apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ml-ms
  name: ml-backend-deployment
  labels:
    app: ml-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-backend
  template:
    metadata:
      labels:
        app: ml-backend
    spec:
      containers:
      - name: ml-backend
        image: fosefx/ml-ms-ml-backend:0.1.1
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: ml-backend-service
  namespace: ml-ms
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    app: ml-backend-service
