# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ml.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x08ml.proto\"+\n\x1aImageClassificationRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"5\n\x1bImageClassificationResponse\x12\x16\n\x0eresultReadable\x18\x01 \x01(\t2Y\n\tMLBackend\x12L\n\rClassifyImage\x12\x1b.ImageClassificationRequest\x1a\x1c.ImageClassificationResponse\"\x00\x62\x06proto3')
)




_IMAGECLASSIFICATIONREQUEST = _descriptor.Descriptor(
  name='ImageClassificationRequest',
  full_name='ImageClassificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='ImageClassificationRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=55,
)


_IMAGECLASSIFICATIONRESPONSE = _descriptor.Descriptor(
  name='ImageClassificationResponse',
  full_name='ImageClassificationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultReadable', full_name='ImageClassificationResponse.resultReadable', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['ImageClassificationRequest'] = _IMAGECLASSIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['ImageClassificationResponse'] = _IMAGECLASSIFICATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageClassificationRequest = _reflection.GeneratedProtocolMessageType('ImageClassificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGECLASSIFICATIONREQUEST,
  '__module__' : 'ml_pb2'
  # @@protoc_insertion_point(class_scope:ImageClassificationRequest)
  })
_sym_db.RegisterMessage(ImageClassificationRequest)

ImageClassificationResponse = _reflection.GeneratedProtocolMessageType('ImageClassificationResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMAGECLASSIFICATIONRESPONSE,
  '__module__' : 'ml_pb2'
  # @@protoc_insertion_point(class_scope:ImageClassificationResponse)
  })
_sym_db.RegisterMessage(ImageClassificationResponse)



_MLBACKEND = _descriptor.ServiceDescriptor(
  name='MLBackend',
  full_name='MLBackend',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=112,
  serialized_end=201,
  methods=[
  _descriptor.MethodDescriptor(
    name='ClassifyImage',
    full_name='MLBackend.ClassifyImage',
    index=0,
    containing_service=None,
    input_type=_IMAGECLASSIFICATIONREQUEST,
    output_type=_IMAGECLASSIFICATIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MLBACKEND)

DESCRIPTOR.services_by_name['MLBackend'] = _MLBACKEND

# @@protoc_insertion_point(module_scope)
